title = ">./Crowdtainer.io"
baseURL = "/"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
#SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  custom_css = ["css/custom.css"]
  body_classes = "avenir bg-white"
  favicon = "images/CrowdtainerLogo.svg"
  description = "combine(delicious_coffee, positive_social_impact)"
  facebook = ""
  twitter = "https://twitter.com/crowdtainer"
  instagram = ""
  youtube = ""
  github = "https://github.com/crowdtainer"
  gitlab = ""
  linkedin = ""
  background_color_class = "bg-near-black"

  recent_posts_number = 2
